In [1]:
import torch
import math
from torch import nn
from torch.optim import SGD

In [8]:
# 准备数据
w = torch.tensor([1,2,3],dtype=torch.float)
x = torch.rand([500,3])
y_true = torch.matmul(x, w).reshape(-1,1)

In [9]:
x

tensor([[0.3835, 0.6539, 0.4848],
        [0.2161, 0.8714, 0.3643],
        [0.1386, 0.7482, 0.5450],
        ...,
        [0.2010, 0.2092, 0.1952],
        [0.2488, 0.8448, 0.3810],
        [0.5992, 0.2802, 0.9151]])

In [10]:
y_true.shape

torch.Size([500, 1])

In [11]:
# 定义模型
class Lr(nn.Module):
    def __init__(self):
        super(Lr,self).__init__()
        self.linear = nn.Linear(3,1, bias=False) # 两个参数，分别是input 的特征和output的特征
    def forward(self, x):
        out = self.linear(x)
        return out
MyLinear = Lr()
optimizer = SGD(MyLinear.parameters(),0.01)
mse_loss = nn.MSELoss()

In [12]:
list(MyLinear.parameters())

[Parameter containing:
 tensor([[-0.5299, -0.5081, -0.3143]], requires_grad=True)]

In [13]:
# 循环、参数更新
for i in range(5000):
    y_predict = MyLinear(x)
    loss = mse_loss(y_predict, y_true)
    optimizer.zero_grad() # 梯度变为零
    loss.backward()
    optimizer.step()
print(loss.item(),list(MyLinear.parameters()))

1.939403837525333e-08 [Parameter containing:
tensor([[1.0003, 2.0000, 2.9996]], requires_grad=True)]
