In [2]:
import torch
from torch import nn

In [46]:
def dropout(x,p):
    print(p)
    assert 0<=p<=1
    if p==1:
        return torch.zeros_like(x)
    if p==0:
        return x
    mask = (torch.randn(x.shape)>p).float()
    return mask*x/(1-p)

In [47]:
x = torch.randn(16,dtype=torch.float32).reshape(2,8)

In [48]:
dropout(x,0.5)

0.5


tensor([[ 0.6484,  2.8415, -1.3070, -0.0000, -0.1905,  0.0000,  1.5714, -0.0000],
        [ 0.0000,  0.0000,  0.0000, -2.2445,  0.0000, -0.0000, -0.0000, -0.0000]])

In [22]:
a = [1,2,3,4]


In [24]:
a = torch.Tensor(a)

In [36]:
(a>2).float()

tensor([0., 0., 1., 1.])

In [44]:
a = torch.randn(2,3)
a


tensor([[-1.0675,  1.1830,  1.5067],
        [-0.0137, -0.8879,  0.0106]])

In [45]:
a>0.5

tensor([[False,  True,  True],
        [False, False, False]])