In [4]:
"""
batch=3, nc = 4
"""
import numpy as np

target = np.array([
    [-1.0606, 1.5613, 1.2007, -0.2481],
    [-1.9652, -0.4367, -0.0645, -0.5104],
    [0.1011, -0.5904, 0.0243, 0.1002]
])

label = np.array([0, 2, 1])


def np_softmax(arr):
    assert len(arr.shape) == 2
    arr_exp = np.exp(arr)
    arr_sum = np.sum(arr_exp, axis=1)  # (3,4) -->(3,)
    arr_sum = arr_sum[:, None]  # 增加维度，才可以通过广播，进行矩阵除法。(3, )-->(3, 1)
    return arr_exp / arr_sum

In [2]:
def np_onehot(nc, true_label):
    """
    param nc: nc代表划分的类别数目
    param true_label: 传入的标签 shape :（batch, )
    return: 返回一个(batch, nc)形式的one_hot变量
    """
    tmp = np.arange(nc)
    tmp = tmp[None, :]  # 增加行的维度，[0,1,2,3] -->[[0, 1, 2, 3]] 。后续才能广播，每一行都是0,1,2,3
    true_label = true_label[:, None]  # 增加列的维度，[0, 2, 1] -->[[0],[2],[1]] 。按照列广播
    ans = tmp == true_label  # 自动广播，返回(batch, nc)形式，为True或False
    return ans.astype(int)  # bool --> int

In [11]:
# 1.对预测结果softmax处理
target_soft = np_softmax(target)
print('target_soft', target_soft)
# 2. 取log对数
target_log = np.log(target_soft)
# 3. one-hot变量
label_one = np_onehot(4, label)
print('label_one', label_one)
# 4. python矩阵乘法，按照元素相乘； 取负数  ， 负对数
res = -target_log * label_one
print('res', res)
# 5. 按照列求和， 取均值
loss = np.mean(np.sum(res, axis=1))

print(loss)

target_soft [[0.03757853 0.51715002 0.36058691 0.08468454]
 [0.06029378 0.27803    0.40340016 0.25827606]
 [0.2918856  0.14618339 0.27030798 0.29162303]]
label_one [[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
res [[3.28132227 0.         0.         0.        ]
 [0.         0.         0.90782626 0.        ]
 [0.         1.92289332 0.         0.        ]]
2.0373472850337726


In [15]:
a = np.array([1,2,3])
num = 4

In [18]:
b = np.arange(0,num)
b = b[None,:]
c = b==a[:,None]
c.astype(int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
import torch
v = torch.rand(512,10)
v.shape

torch.Size([512, 10])

In [20]:
v.reshape(-1,1).shape

torch.Size([5120, 1])